# Generated by Django 5.1.7 on 2025-03-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_category_custom_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='page_type',
            field=models.CharField(choices=[('note', 'Note'), ('guide', 'Guide')], default='note', max_length=10),
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('step_content', models.TextField()),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_steps', to='wiki.wikipage')),
            ],
        ),
    ]
