# Generated by Django 5.1.7 on 2025-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikipage_page_type_guidestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='guide_steps/'),
        ),
        migrations.AlterField(
            model_name='guidestep',
            name='step_order',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
